### ISSUE TITLE
bundle won't work < symfony3.3

### ISSUE THREAD

**Issue by webspin** [expertcoder/SwiftmailerSendGridBundle#10]
> The arrayPrototype() method (and the related booleanPrototype() integerPrototype(), floatPrototype(), scalarPrototype() and enumPrototype()) was introduced in Symfony 3.3. In previous versions, you needed to use prototype('array'), prototype('boolean'), etc.

**Comment by moux2003** [comment]
@webspin Thanks, I'll fix this soon.

@expertcoder can you add this project to Travis-CI (only you can do it) ? ([https://travis-ci.org](https://travis-ci.org))

**Comment by expertcoder** [comment]
Hi, ill add this to travis-CI in the next day or 2.

**Comment by expertcoder** [comment]
Travis-CI enabled, let me know if there is anything else you need.
