### ISSUE TITLE
Installation fails on Symfony 4.0

### ISSUE THREAD

**Issue by martijnhartlief** [expertcoder/SwiftmailerSendGridBundle#12]
Using version ^1.1 for expertcoder/swiftmailer-send-grid-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for __root__ dev-master -> satisfiable by __root__[dev-master].
    - expertcoder/swiftmailer-send-grid-bundle 1.1.0 requires symfony/symfony ~2.7|~3.3|~4.0 -> satisfiable by symfony/symfony[v2.7.0, v2.7.1, v2.7.10, ...

**Comment by moux2003** [comment]
This bundle is not yet compatible with Flex & recipe system, so you need to use full standard framework in order to use this bundle as of now. 

Feel free to contribute if you can :)

**Comment by martijnhartlief** [comment]
I'm using "symfony/framework-bundle": "^4.0"

I would love to contribute, if you can point me at the reason why  'root dev-master' is the version it tries to install. Because that is the part I've never seen before.

**Comment by moux2003** [comment]
I think it's due to the new default composer.json property:
```
"conflict": {
        "symfony/symfony": "*"
    },
```
This bundle should not use symfony/symfony anymore but instead include every symfony components needed and define a recipe to be fully ready for Sf4

**Comment by moux2003** [comment]
@martijnhartlief Hi, just to let you know that the last release (2.1.0) is ready for Symfony 4 and flex system. I'm still waiting for the recipe to be merged (https://github.com/symfony/recipes-contrib/pull/391).
Feel free to reopen the issue if something went wrong

**Comment by moux2003** [comment]
@expertcoder can you review this PR https://github.com/symfony/recipes-contrib/pull/391 to validate please
