### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by marvoh** [expertcoder/SwiftmailerSendGridBundle#14]
I'm getting error below after installation. What could be the issue 

Unable to replace alias "swiftmailer.mailer.default.transport.real" with actual definition "expertcoder_swift_mailer.send_grid".

**Comment by marvoh** [comment]
I edited the service id at vendor/expertcoder/swiftmailer-send-grid-bundle/src/Resources/Services.xml from swiftmailer.mailer.default.transport.expertcoder_swift_mailer.send_grid to expertcoder_swift_mailer.send_grid. Let me know how to solve this permanently

**Comment by moux2003** [comment]
@marvoh  can you give us more details please.
What is your symfony version/distribution ?
Are you using v1 or v2 of this bundle ?

Can you also check that you have set the right configuration like so:
```yml
swiftmailer:
    transport: expertcoder_swift_mailer.send_grid
```

**Comment by marvoh** [comment]
Sorry for the scant information. I am using symfony verion 3.4.13 and v2 of the bundle.

I have also encountered another issue when trying to send an email.

Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Mail" from namespace "SendGrid". Did you forget a "use" statement for e.g. "SendGrid\Mail\Mail" or "SendGrid\mail\Mail"?" at /vendor/expertcoder/swiftmailer-send-grid-bundle/src/Services/SendGridTransport.php line 100

**Comment by moux2003** [comment]
Can you give your configuration from config_dev.yml and config.yml ?

**Comment by ventuc** [comment]
Same problem here with Symfony 3.4 and bundle 2.1. Actually the name of the transport service appears to be different, in fact it is `swiftmailer.mailer.transport.expertcoder_swift_mailer.send_grid` and not simply `expertcoder_swift_mailer.send_grid`.

So change the configuration as follows:

```
swiftmailer:
    transport: 'swiftmailer.mailer.transport.expertcoder_swift_mailer.send_grid'
```

Hope this can help
