### ISSUE TITLE
Support plugins

### ISSUE THREAD

**Issue by geekdevs** [expertcoder/SwiftmailerSendGridBundle#19]
Thanks for this nice bundle!
I could test this successfully, but noticed that plugins architecture of SwiftMailer is not implemented.

For instance, I wanted to use symfony's `delivery_addresses` feature (https://symfony.com/doc/current/email/dev_environment.html) but it does not work with this transport. Is there any reason why plugins registering is skipped?

**Comment by moux2003** [comment]
There is no reason , could be interesting to improve the transport part

**Comment by geekdevs** [comment]
@moux2003 Alright, I created PR for this here https://github.com/expertcoder/SwiftmailerSendGridBundle/pull/20

I could successfully test this with `delivery_addresses` feature on my project.

**Comment by moux2003** [comment]
Thanks for the contrib
