### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by DeathByLasers** [expertcoder/SwiftmailerSendGridBundle#23]
Warning: count(): Parameter must be an array or an object that implements Countable

in vendor/expertcoder/swiftmailer-send-grid-bundle/src/Services/SendGridTransport.php (line 263)
if ($sent == count($toArr) + count($ccArr) + count($bccArr))

**Comment by moux2003** [comment]
Fixed by commit a49bfbf01ec28c9bdc4f9a0797083cbb7ed98f5b
