### ISSUE TITLE
Error when sending emails

### ISSUE THREAD

**Issue by djardine** [expertcoder/SwiftmailerSendGridBundle#5]
Using symfony 2.7 I get the following error when attempting to send an email via swiftmail:

> Notice: Undefined property: SendGrid\Response::$_status_code

```
        // only 2xx status are ok
        if (
                $response->_status_code < self::STATUS_OK_SUCCESSFUL_MIN_RANGE || 
                self::STATUS_SUCCESSFUL_MAX_RANGE < $response->_status_code ) {
            
            // to force big boom error uncomment this line
```

Maybe the sendgrid php library has breaking changes?

**Comment by expertcoder** [comment]
I'm guessing the`sendgrid\sendgrid` library had changed. Also there is now version 6 of `sendgrid\sendgrid`. Feel free to make a pull request to fix this issue, and even consider upgrading to version 6 of `sendgrid\sendgrid`

**Comment by joubertredrat** [comment]
Same issue here, I will try to fix here.

**Comment by expertcoder** [comment]
Thanks for the pull request, I have merged it. I didn't test it myself
