### ISSUE TITLE
Refactor and tag versions

### ISSUE THREAD

**Issue by joubertredrat** [expertcoder/SwiftmailerSendGridBundle#7]
Hi @expertcoder,

You have plans to refactor and tag this bundle? I saw here that is possible to improve code quality.

What you think?

**Comment by expertcoder** [comment]
Hi,

I personally have not used this bundle in a few years. Please feel free to contribute any improvements. I have added you as a collaborator to the project, I assume you will have the permissions you need to make changes.

I was lazy and never bothered to tag.
You may be aware its still possible to lock non tagged repos in `composer.json` by doing something like

```
     "expertcoder/swiftmailer-send-grid-bundle": "@dev#739a34d0bc0...."
```
Where `739a34d0bc0....` is a git commit reference.

Thanks for your interest in the project.

**Comment by joubertredrat** [comment]
Thanks @expertcoder by trust. I will create a PR with simple refactors and discuss on then.
